In [3]:
import pandas as pd
df0 = pd.read_csv('clean.txt')

def quickpeek(df):
    print(df.shape)
    print(f"{df['player'].nunique()} QBs")
    display(df.head())

quickpeek(df0)

(8723, 10)
136 QBs

,player,season,quint,home,cmp%,attempts,ny/a,carries,ypc,td:to
0,Geno Smith,2013,2,1,0.400000,10,1.909091,1,2.000000,-1
1,Ryan Tannehill,2013,2,0,0.651163,43,7.454545,3,7.333333,1
2,Brandon Weeden,2013,2,1,0.600000,40,7.953488,2,2.500000,-1
3,Joe Flacco,2013,2,1,0.685714,35,6.405405,4,1.750000,0
4,Matt Flynn,2013,2,0,0.500000,20,3.777778,2,2.000000,-3

In [4]:
# standardize playing stats by league year
# (justification for this can be found in `change-over-year.ipynb`)
stats = ['cmp%', 'attempts', 'ny/a', 'carries', 'ypc', 'td:to']
years = df0['season'].unique()

df1 = df0.copy()
for s in stats:
    for yr in years:
        onestatoneyear = df0[df0['season'] == yr][s]
        m = onestatoneyear.mean()
        sd = onestatoneyear.std()
        df1.loc[df1['season'] == yr, s] = (onestatoneyear - m) / sd

quickpeek(df1)

(8723, 10)
136 QBs

,player,season,quint,home,cmp%,attempts,ny/a,carries,ypc,td:to
0,Geno Smith,2013,2,1,-1.731589,-1.929814,-1.996211,-0.745945,-0.333316,-0.660409
1,Ryan Tannehill,2013,2,0,0.355435,0.921932,0.537252,0.029335,0.932606,0.417611
2,Brandon Weeden,2013,2,1,-0.069699,0.662682,0.765196,-0.358305,-0.214636,-0.660409
3,Joe Flacco,2013,2,1,0.642539,0.230600,0.057949,0.416975,-0.392656,-0.121399
4,Matt Flynn,2013,2,0,-0.900644,-1.065648,-1.142494,-0.358305,-0.333316,-1.738429

In [6]:
# standardize metadata
# (justification: so that everything has the same "unit")
nonstats = ['season', 'quint', 'home']

df2 = df1.copy()
for col in nonstats:
    df2[col] = (df1[col] - df1[col].mean()) / df1[col].std()

quickpeek(df2)

(8723, 10)
136 QBs

,player,season,quint,home,cmp%,attempts,ny/a,carries,ypc,td:to
0,Geno Smith,0.424688,0.360108,0.998912,-1.731589,-1.929814,-1.996211,-0.745945,-0.333316,-0.660409
1,Ryan Tannehill,0.424688,0.360108,-1.000975,0.355435,0.921932,0.537252,0.029335,0.932606,0.417611
2,Brandon Weeden,0.424688,0.360108,0.998912,-0.069699,0.662682,0.765196,-0.358305,-0.214636,-0.660409
3,Joe Flacco,0.424688,0.360108,0.998912,0.642539,0.230600,0.057949,0.416975,-0.392656,-0.121399
4,Matt Flynn,0.424688,0.360108,-1.000975,-0.900644,-1.065648,-1.142494,-0.358305,-0.333316,-1.738429

In [7]:
df2.to_csv('standard.txt', index=False)